version: '3'
services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./.log:/var/log/odoo
      - ../base-addons/base_extended_security:/mnt/extra-addons/base_extended_security
      - ../base-addons/private_data_group:/mnt/extra-addons/private_data_group
      - ../base-addons/test_http_request:/mnt/extra-addons/test_http_request
      - ./hr_employee_private_wizard:/mnt/extra-addons/hr_employee_private_wizard
      - ./hr_employee_type:/mnt/extra-addons/hr_employee_type
      - ./hr_employee_type_private_wizard:/mnt/extra-addons/hr_employee_type_private_wizard
    ports:
      - "8069:8069"
      - "8071:8071"
    depends_on:
      - db
    command: odoo
    environment:
      - LOG_ODOO=/var/log/odoo
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    expose:
      - 5432

volumes:
  odoo-web-data:
  odoo-db-data:
